### ISSUE TITLE
how to define multiple bc_desktop entries ?

### ISSUE THREAD

**Issue by xpillons** [OSC/ood-ansible#126] opened 2021-09-29 10:56 UTC
I would like to be able to add several entries for bc_desktop on the same cluster, for example one GPU accelerated and one CPU like this : 
```yml
ood_apps:
  bc_desktop:
    title: "desktop 1"
  bc_desktop:
    title: "desktop 2"
```

but this looks not possible as I'm having this warning. 
 "[WARNING]: While constructing a mapping from /hpc/playbooks/ood-overrides.yml, line 36, column 3, found a duplicate dict key (bc_desktop). Using last defined value only."

How to add multiple entries here ?

**Comment by johrstrom** [comment] 2021-09-29 13:38
Unfortunately I don't think you can. It's a duplicate of #77.  I haven't looked up how to do this in a backward compatible way, or at least haven't decided to break it.

**Comment by johrstrom** [comment] 2021-09-29 13:39
Pull requests welcome if you can figure out how to do it in a backward compatible way!

**Closed by johrstrom** 2021-09-29 13:38 UTC
